export { default as StarIcon } from '@material-ui/icons/Star';
export { default as MenuIcon } from '@material-ui/icons/Menu';
export { default as ClearIcon } from '@material-ui/icons/Clear';
export { default as LaunchIcon } from '@material-ui/icons/Launch';
export { default as ChromeReaderMode } from '@material-ui/icons/ChromeReaderMode';
export { LogoWithNameIcon } from './LogoWithNameIcon';
export { MediumIcon } from './MediumIcon';
export { TwitterIcon } from './TwitterIcon';
export { ChevronRightIcon } from './ChevronRightIcon';
export { GithubIcon } from './GithubIcon';
export { LinkedinIcon } from './LinkedinIcon';
export { TelegramIcon } from './TelegramIcon';
export { RiotIcon } from './RiotIcon';
export { DiscordIcon } from './DiscordIcon';
export { getSocialIconByLink } from './getSocialIconByLink';
export * from './Sun';
export * from './Moon';
export * from './MainSvgGradient';
